# render.yaml
services:
  - type: web
    name: sales-analytics-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false # Isso indica que a variável será configurada manualmente no dashboard do Render
    healthCheckPath: /health
    autoDeploy: true
